#提示信息前缀
prompt-prefix: '&6生存专家'

#菜单配置
menu:
  #边角填充方块配置
  common:
    corner:
      material: MAGENTA_STAINED_GLASS_PANE
      durability: 0
    border:
      material: BLUE_STAINED_GLASS_PANE
      durability: 0
  #主菜单配置
  main:
    title: '&6&l生存专家'
    button:
      equip:
        name: '&b宝石装备'
        lore:
          - '&e装备&d战斗&e宝石以提升&d打出伤害'
          - '&e装备&a生命&e宝石以降低&a所受伤害'
          - ''
          - '&3左键打开 &1| &3右键获取快捷方式'
        item:
          material: LIME_SHULKER_BOX
          durability: 0
      upgrade:
        name: '&b宝石升级'
        lore:
          - '&e将两颗同类型、 同等级的'
          - '&e宝石合成为高一级的一颗'
          - '&e宝石， 失败会使一颗消失'
        item:
          material: RED_SHULKER_BOX
          durability: 0
      ranking:
        name: '&b点数排行'
        lore:
          - '&e查看全服战斗与生命点数'
          - '&e的前十名， 还有你的排名'
        item:
          material: LIGHT_BLUE_SHULKER_BOX
          durability: 0
      battle:
        name: '&d战斗&b点数宝石兑换'
        lore:
          - '&e用&d{ratio}&e战斗点数兑换1个一级&d战斗&e宝石'
          - ''
          - '&e战斗点数： {total}'
          - '&e可用点数： {usable}'
          - '&e可换个数： {number}'
          - ''
          - '&3左键兑换一个 &1| &3右键兑换全部'
        item:
          material: MAGMA_CREAM
          durability: 0
      life:
        name: '&a生命&b点数宝石兑换'
        lore:
          - '&e用&a{ratio}&e生命点数兑换1个一级&a生命&e宝石'
          - ''
          - '&e生命点数： {total}'
          - '&e可用点数： {usable}'
          - '&e可换个数： {number}'
          - ''
          - '&3左键兑换一个 &1| &3右键兑换全部'
        item:
          material: SLIME_BALL
          durability: 0
      desc:
        name: '&b点数获得方法'
        lore:
          - '&d战斗&e点数在挖掘矿物时有一定几率获得'
          - '&a生命&e点数在采集作物时有一定几率获得'
          - ''
          - '&3点击查看所有有效的矿物和作物'
        item:
          material: FIRE_CHARGE
          durability: 0
  #装备菜单配置
  equip:
    title: '&6&l宝石装备'
    #为空时宝石槽的配置
    slot:
      battle:
        name: '&d战斗&b宝石槽'
        lore:
          - '&e将你的战斗宝石放在此处'
          - '&e放入后将获得百分之十乘'
          - '&e宝石等级的打出伤害加成'
        item:
          material: WHITE_STAINED_GLASS_PANE
          durability: 0
      life:
        name: '&a生命&b宝石槽'
        lore:
          - '&e将你的战斗宝石放在此处'
          - '&e放入后将获得百分之十乘'
          - '&e宝石等级的所受伤害减免'
        item:
          material: WHITE_STAINED_GLASS_PANE
          durability: 0
  upgrade:
    title: '&6&l宝石升级'
    #宝石槽的配置
    slot:
      name: '&b宝石槽'
      lore:
        - '&e请将两个类型、 等级相同的宝'
        - '&e石放在两侧， 放入后将在下方'
        - '&e显示成功率以及成功时的产物'
      item:
        material: WHITE_STAINED_GLASS_PANE
        durability: 0
    #显示几率的配置
    rate:
      name: '&b成功率【 &e{rate} &b】'
      lore:
        - '&e如果合成成功， 则宝'
        - '&e石等级加一； 如果失'
        - '&e败， 则失去其中一颗'
      item:
        material: HOPPER
        durability: 0
  ranking:
    title: '&6&l点数排行'
    battle:
      name: '&d战斗专家： &a{name}'
      lore:
        - '&e战斗点数： {total}'
        - '&e宝石等级： {level}'
      empty:
        name: '&e虚位以待'
        item:
          material: PINK_STAINED_GLASS_PANE
          durability: 0
    life:
      name: '&a生命专家： &a{name}'
      lore:
        - '&e生命点数： {total}'
        - '&e宝石等级： {level}'
      empty:
        name: '&e虚位以待'
        item:
          material: LIME_STAINED_GLASS_PANE
          durability: 0
    mine:
      name: '&b我的排名'
      lore:
        - '&e战斗点数： {battleTotal}'
        - '&e战斗排名： {battleRank}'
        - '&e生命点数： {lifeTotal}'
        - '&e生命排名： {lifeRank}'
  enum:
    title: '&6&l矿物/作物枚举'
    block:
      name: '{type}&e： {name}'

#宝石配置
gem:
  #战斗宝石
  battle:
    name: '&7[&6生存专家&7]&d战斗&b宝石&7[&eLv.{level}&7]'
    lore:
      - '&e这是由生存者的劳动凝成的精华'
      - '&e由挖掘矿物产生的战斗点数换得'
      - '&e提供等级乘百分之十的伤害加成'
    item:
      material: MAGMA_CREAM
      durability: 0
    #每级伤害值加成比率
    bonus-percentage: 0.1
  #生命宝石
  life:
    name: '&7[&6生存专家&7]&a生命&b宝石&7[&eLv.{level}&7]'
    lore:
      - '&e这是由生存者的劳动凝成的精华'
      - '&e由采集作物产生的生存点数换得'
      - '&e提供等级乘百分之十的伤害减免'
    item:
      material: SLIME_BALL
      durability: 0
    #每级伤害值减免比率
    bonus-percentage: 0.1
  shortcut:
    name: '&7[&6生存专家&7]&b宝石装备栏'
    lore:
      - '&e右键可直接打开宝石装备栏'
    item:
      material: SNOWBALL
      durability: 0

#全局配置
setting:
  #点数兑换比例
  point-exchange-ratio: 100
  #成功率基数，每级成功率为基数的原等级次方，如2级升3级，成功率是0.8的2次方0.64
  success-rate-base: 0.8
  #矿物配置
  ore:
    #矿物方块配置
    blocks: COAL_ORE,IRON_ORE,GOLD_ORE,DIAMOND_ORE,EMERALD_ORE,LAPIS_ORE,REDSTONE_ORE,NETHER_QUARTZ_ORE
    #获取战斗点数的几率
    chance: 0.1
  #作物配置
  crop:
    #作物方块配置
    blocks: WHEAT,CARROTS,POTATOS,BEETROOTS,COCOA,NETHER_WARTS,CHORUS_FLOWER,SUGAR_CANE,PUMPKIN,MELON,CACTUS,BAMBOO
    #获取生命点数的几率
    chance: 0.1

#提示信息
message:
  reload-success: '&e配置信息重载成功'
  invaild-player: '&e目标玩家不在线'
  invaild-param: '&e参数无效， 请检查后重试'
  give-gem: '&e你已获得 &b{number} &e个等级 &b{level} &e的 {type} &e宝石'
  inventory-full: '&e你的背包已满， 无法获得目标物品'
  give-success: '&e成功将宝石给予目标玩家'
  give-failed: '&e目标玩家背包已满， 执行失败'
  points-modify: '&e你的 {type} &e点数已被修改为 &b{number}'
  modify-success: '&e操作成功完成'
  exchage-success: '&e成功兑换 &b{number} &e个 {type} &e宝石'
  get-shortcut: '&e成功将快捷方式添加至你的背包'
  player-only: '&e控制台无法打开GUI菜单'
  not-enough: '&e你的点数不足以进行兑换'
  earn-point: '&e恭喜你获得 &b1 {type} &e点数， 总点数 &b{total}'
  gem-equip: '&e成功装备 {type} &e宝石， 等级 &b{level}'
  un-equip: '&e你卸下了你的宝石， 加成将被移除'
  up-success: '&e恭喜！ 宝石升级成功！'
  up-failed: '&e哦不！ 你失去了一半的宝石'
  boardcast:
    upgrade: '&c{name}&e已经成功合成出&b{level}&e级{type}&e宝石！'
    kill: '&c{killer}&e携带&b{battleLevel}&e级{battle}&e宝石&b{lifeLevel}&e级{life}&e宝石击杀了&c{dead}'
  type:
    ore: '&d矿石'
    crop: '&a作物'
    battle: '&d战斗'
    life: '&a生命'

help:
  equip: '&e打开宝石装备GUI菜单'
  upgrade: '&e打开宝石升级GUI菜单'
  ranking: '&e打开点数排名GUI菜单'
  enum: '&e打开矿物/作物枚举GUI菜单'
  give: '&e给予指定玩家指定类型、 等级和数量的宝石'
  point: '&e调整玩家的战斗或生命点数'
  reload: '&e重载插件配置文件'