name: ${artifactId}
main: cn.daniellee.plugin.se.SurvivalExpert
version: ${version}
api-version: 1.13
commands:
  survivalexpert:
    usage: /<command>
    aliases: [se, expert, survival]
    description: SurvivalExpert

permissions:
  expert.command.*:
    description: ability to use all commands
    children:
      expert.command.give: true
      expert.command.reload: true
  expert.command.give:
    description: ability to use give command
  expert.command.reload:
    description: ability to use reload command